language: cpp
sudo: false
compiler:
  - gcc
os:
  - linux
notifications:
  slack: kronosus:1qazkyb5u4Kx7Rtqlk8IB83b
addons:
  apt:
    sources:
      # For cmake >= 2.8.8
      - kubuntu-backports
    packages:
      - libqt4
      - cmake
      - doxygen
script:
  - make
