# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bbq/Projects/STUPRO_new

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bbq/Projects/STUPRO_new

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bbq/Projects/STUPRO_new/CMakeFiles /home/bbq/Projects/STUPRO_new/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bbq/Projects/STUPRO_new/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named globe

# Build rule for target.
globe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 globe
.PHONY : globe

# fast build rule for target.
globe/fast:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/build
.PHONY : globe/fast

src/Globe.o: src/Globe.cpp.o
.PHONY : src/Globe.o

# target to build an object file
src/Globe.cpp.o:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Globe.cpp.o
.PHONY : src/Globe.cpp.o

src/Globe.i: src/Globe.cpp.i
.PHONY : src/Globe.i

# target to preprocess a source file
src/Globe.cpp.i:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Globe.cpp.i
.PHONY : src/Globe.cpp.i

src/Globe.s: src/Globe.cpp.s
.PHONY : src/Globe.s

# target to generate assembly for a file
src/Globe.cpp.s:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Globe.cpp.s
.PHONY : src/Globe.cpp.s

src/GlobeTile.o: src/GlobeTile.cpp.o
.PHONY : src/GlobeTile.o

# target to build an object file
src/GlobeTile.cpp.o:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/GlobeTile.cpp.o
.PHONY : src/GlobeTile.cpp.o

src/GlobeTile.i: src/GlobeTile.cpp.i
.PHONY : src/GlobeTile.i

# target to preprocess a source file
src/GlobeTile.cpp.i:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/GlobeTile.cpp.i
.PHONY : src/GlobeTile.cpp.i

src/GlobeTile.s: src/GlobeTile.cpp.s
.PHONY : src/GlobeTile.s

# target to generate assembly for a file
src/GlobeTile.cpp.s:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/GlobeTile.cpp.s
.PHONY : src/GlobeTile.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/StuproApplication.o: src/StuproApplication.cpp.o
.PHONY : src/StuproApplication.o

# target to build an object file
src/StuproApplication.cpp.o:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/StuproApplication.cpp.o
.PHONY : src/StuproApplication.cpp.o

src/StuproApplication.i: src/StuproApplication.cpp.i
.PHONY : src/StuproApplication.i

# target to preprocess a source file
src/StuproApplication.cpp.i:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/StuproApplication.cpp.i
.PHONY : src/StuproApplication.cpp.i

src/StuproApplication.s: src/StuproApplication.cpp.s
.PHONY : src/StuproApplication.s

# target to generate assembly for a file
src/StuproApplication.cpp.s:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/StuproApplication.cpp.s
.PHONY : src/StuproApplication.cpp.s

src/StuproInteractor.o: src/StuproInteractor.cpp.o
.PHONY : src/StuproInteractor.o

# target to build an object file
src/StuproInteractor.cpp.o:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/StuproInteractor.cpp.o
.PHONY : src/StuproInteractor.cpp.o

src/StuproInteractor.i: src/StuproInteractor.cpp.i
.PHONY : src/StuproInteractor.i

# target to preprocess a source file
src/StuproInteractor.cpp.i:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/StuproInteractor.cpp.i
.PHONY : src/StuproInteractor.cpp.i

src/StuproInteractor.s: src/StuproInteractor.cpp.s
.PHONY : src/StuproInteractor.s

# target to generate assembly for a file
src/StuproInteractor.cpp.s:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/StuproInteractor.cpp.s
.PHONY : src/StuproInteractor.cpp.s

src/TextureLoad.o: src/TextureLoad.cpp.o
.PHONY : src/TextureLoad.o

# target to build an object file
src/TextureLoad.cpp.o:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/TextureLoad.cpp.o
.PHONY : src/TextureLoad.cpp.o

src/TextureLoad.i: src/TextureLoad.cpp.i
.PHONY : src/TextureLoad.i

# target to preprocess a source file
src/TextureLoad.cpp.i:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/TextureLoad.cpp.i
.PHONY : src/TextureLoad.cpp.i

src/TextureLoad.s: src/TextureLoad.cpp.s
.PHONY : src/TextureLoad.s

# target to generate assembly for a file
src/TextureLoad.cpp.s:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/TextureLoad.cpp.s
.PHONY : src/TextureLoad.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/VTKOpenGL.o: src/VTKOpenGL.cpp.o
.PHONY : src/VTKOpenGL.o

# target to build an object file
src/VTKOpenGL.cpp.o:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/VTKOpenGL.cpp.o
.PHONY : src/VTKOpenGL.cpp.o

src/VTKOpenGL.i: src/VTKOpenGL.cpp.i
.PHONY : src/VTKOpenGL.i

# target to preprocess a source file
src/VTKOpenGL.cpp.i:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/VTKOpenGL.cpp.i
.PHONY : src/VTKOpenGL.cpp.i

src/VTKOpenGL.s: src/VTKOpenGL.cpp.s
.PHONY : src/VTKOpenGL.s

# target to generate assembly for a file
src/VTKOpenGL.cpp.s:
	$(MAKE) -f CMakeFiles/globe.dir/build.make CMakeFiles/globe.dir/src/VTKOpenGL.cpp.s
.PHONY : src/VTKOpenGL.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... globe"
	@echo "... src/Globe.o"
	@echo "... src/Globe.i"
	@echo "... src/Globe.s"
	@echo "... src/GlobeTile.o"
	@echo "... src/GlobeTile.i"
	@echo "... src/GlobeTile.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/StuproApplication.o"
	@echo "... src/StuproApplication.i"
	@echo "... src/StuproApplication.s"
	@echo "... src/StuproInteractor.o"
	@echo "... src/StuproInteractor.i"
	@echo "... src/StuproInteractor.s"
	@echo "... src/TextureLoad.o"
	@echo "... src/TextureLoad.i"
	@echo "... src/TextureLoad.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/VTKOpenGL.o"
	@echo "... src/VTKOpenGL.i"
	@echo "... src/VTKOpenGL.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

